Create databases and tables, insert small amounts of data, and run simple queries using Impala

In [1]:
# Importing Packages
import sqlite3
import pandas as pd

In [2]:
# Connecting to the Impla Server
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

print("Database created successfully!")

Database created successfully!

In [4]:
cursor.execute("""
CREATE TABLE students (
    student_id INTEGER,
    name TEXT,
    age INTEGER,
    course TEXT,
    marks REAL
)
""")

print("Table 'students' created!")

Table 'students' created!

In [5]:
students_data = [
    (1, 'Rohan', 21, 'AI', 85.5),
    (2, 'Amit', 22, 'DS', 78.0),
    (3, 'Priya', 20, 'AI', 92.3),
    (4, 'Sneha', 21, 'ML', 88.8),
    (5, 'Karan', 23, 'DS', 67.5)
]

cursor.executemany("INSERT INTO students VALUES (?, ?, ?, ?, ?)", students_data)

conn.commit()
print("Data inserted successfully!")

Data inserted successfully!

In [6]:
df = pd.read_sql_query("SELECT * FROM students", conn)
df

   student_id   name  age course  marks
0           1  Rohan   21     AI   85.5
1           2   Amit   22     DS   78.0
2           3  Priya   20     AI   92.3
3           4  Sneha   21     ML   88.8
4           5  Karan   23     DS   67.5

In [8]:
df = pd.read_sql_query("SELECT name, course FROM students", conn)
df

    name course
0  Rohan     AI
1   Amit     DS
2  Priya     AI
3  Sneha     ML
4  Karan     DS

In [9]:
df = pd.read_sql_query("SELECT * FROM students WHERE marks > 80", conn)
df

   student_id   name  age course  marks
0           1  Rohan   21     AI   85.5
1           3  Priya   20     AI   92.3
2           4  Sneha   21     ML   88.8

In [11]:
df = pd.read_sql_query("SELECT AVG(marks) AS average_marks FROM students", conn)
df

   average_marks
0          82.42

In [13]:
cursor.execute("""
UPDATE students
SET marks = 70
WHERE student_id = 5
""")

conn.commit()

df = pd.read_sql_query("SELECT * FROM students", conn)
df

   student_id   name  age course  marks
0           1  Rohan   21     AI   85.5
1           2   Amit   22     DS   78.0
2           3  Priya   20     AI   92.3
3           4  Sneha   21     ML   88.8
4           5  Karan   23     DS   70.0

In [14]:
cursor.execute("DELETE FROM students WHERE student_id = 2")

conn.commit()

df = pd.read_sql_query("SELECT * FROM students", conn)
df

   student_id   name  age course  marks
0           1  Rohan   21     AI   85.5
1           3  Priya   20     AI   92.3
2           4  Sneha   21     ML   88.8
3           5  Karan   23     DS   70.0

In [15]:
cursor.execute("DROP TABLE students")

print("Table dropped successfully!")

Table dropped successfully!

In [16]:
conn.close()
print("Connection closed!")

Connection closed!